return {
	-- 	{
	-- 		"simrat39/rust-tools.nvim",
	-- 		config = function()
	-- 			local rt = require("rust-tools")
	-- 			-- local ih = require("inlay-hints")
	-- 			require("rust-tools").setup({
	-- 				-- tools = {
	-- 				-- 	on_initialized = function()
	-- 				-- 		ih.set_all()
	-- 				-- 	end,
	-- 				-- 	inlay_hints = {
	-- 				-- 		auto = false,
	-- 				-- 	},
	-- 				-- },
	-- 				server = {
	-- 					on_attach = function(client, bufnr)
	-- 						-- ih.on_attach(client, bufnr)
	-- 						vim.keymap.set("n", "<C-space>", rt.hover_actions.hover_actions, { buffer = bufnr })
	-- 						vim.keymap.set("n", "<leader>a", rt.code_action_group.code_action_group, { buffer = bufnr })
	-- 					end,
	-- 				},
	-- 			})
	-- 		end,
	-- 	},
}
